### ISSUE TITLE
exclude filter in Sanskrit not working

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#105]
The exclude filter in Sanskrit is sometimes not working.
F.I. go to Udanavarga and exclude the Patna Dhammapada - it does not do anything.

**Comment by sebastian-nehrdich** [comment]
I also noted this problem. It has led to the situation that also on the
right side text view, _all_ parallels are displayed instead of only those
that matches with the left-hand text...
