### ISSUE TITLE
Error in limit collection right text view

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#110]
For instance you want text A and limit the collection to B ... fine, it just gives the results for B in A in the left column. Clicking on one gives the right results in the middle column. But then clicking on one of those results opens the right column with the matches between those two texts hightlighted. That's still correct. But then when you click on one of the green areas in the right and nothing appears in the middle because it tries to do so with a filter on B (so on itself) and finds no matches with itself.

**Comment by ayya-vimala** [comment]
This appears in all languages:
Go for instance to D4021 and do a limit filter on D4027 (so it only shows matches between these two files). 
Click on the first blue match and it gives you the parallel in the middle column like this:
![image](https://user-images.githubusercontent.com/49606945/75628535-60028f00-5bda-11ea-8b3d-a2a9abd57312.png)
Sofar so good. Click on the parallel and on the right side appears the text for D4027 with green marked where there is a parallel with D4021. Still good.
![image](https://user-images.githubusercontent.com/49606945/75628569-9b9d5900-5bda-11ea-9d8d-daba02092496.png)

But then click on any of these green parts on the right and you get ... 0 parallels found.
![image](https://user-images.githubusercontent.com/49606945/75628581-ba035480-5bda-11ea-957c-cdbdfbd0d1b9.png)

Why? Because the click initiates a post to the backend asking for the parallels with limit collection D4027 (=itself) so as D4027 does not have any parallels with D4027, you get nothing.

**Comment by sebastian-nehrdich** [comment]
OK this one I could reproduce now. During the meeting today I misunderstood this as the scenario when no filter is active. I will look into it tomorrow!

**Comment by sebastian-nehrdich** [comment]
I think my recent pull-request should fix this. How is it for you @ayya-vimala ?

**Comment by ayya-vimala** [comment]
I think so because I saw the code. But please leave it ... I will have a look tomorrow and hopefully it will all be merged in development then. Bit tired now.

**Comment by ayya-vimala** [comment]
Yes, this works now.
