### ISSUE TITLE
Filters on graphs not working

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#114]
Filter settings work on the total number of matches in graph view but not the graphs itself, at least not on bn2 online. 
I thought this issue had already been solved but will check again.

**Comment by ayya-vimala** [comment]
This works locally so it must be that the online version does not use the latest build for the backend.

**Comment by sebastian-nehrdich** [comment]
yes its purely caused by the build capacities of the server. not enough
memory to complete the entire calculation in one go. Will do that again
once I got my workstation back!

**Comment by ayya-vimala** [comment]
Okay ... will close this point.
