### ISSUE TITLE
Problem with the scroll bars in the text view

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#164]
One quote from one of the reviewers:

"there is a new small problem now that I also noticed myself but forgot to mention. There are some difficulties in scrolling up and down in the columns, due to the fact that the two bars - the one for changing the width and the one for scrolling - kind of clash with each other when pointing with the mouse, i.e., the width bar has the over hand, and it is quite tricky to get the mouse pointed at the scrolling bar. I realized that if I point the mouse to the most left point possible on the bar I can get rid of the width bar horizontal arrow, and can scroll but my colleague didn't realize that."

I think I can reproduce this to some extent when I open the website with Firefox, which prints the scroll bars slightly smaller than chromium and then it indeeds becomes a bit tricky to 'click' on them. For me it doesn't matter terribly much since i use the scroll wheel in 99% of the cases, but some users seem to prefer to click the bars...

**Comment by ayya-vimala** [comment]
This can only be solved by Vaadin I think. It is part of the split-layout.
The other option is simply to click on the scrollbar just above or below the scroller and it will go there. 
Or use the mouse-wheel.

**Comment by sebastian-nehrdich** [comment]
I think the problem boils down to the following:
![scrollbars](https://user-images.githubusercontent.com/18755480/85686082-f0a43400-b6cf-11ea-9828-4be99e284d83.png)
In the blue area of the screenshot, the scroll-bar is not clickable, because the resize-bar  'overlaps' the scroll bar. clicking outside of the blue area, the scroll-bar works as expected. I observe this behavior on chromium.

**Comment by ayya-vimala** [comment]
Yes, that's what I talked about. It becomes unclickable when the scrollbar itself is rather small. But then you can click under or above it and then it works.

**Comment by ayya-vimala** [comment]
Ah ... got it! I had the notation wrong. This is how you do parts:

```
  vaadin-split-layout::part(handle) {
    width: 10px;
  }
```
