### ISSUE TITLE
Regex for collections not precise enough

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#17]
#### Bug Description
Currently the regex for collection keys is:
`([A-Z]*[0-9]+|'XX'|[a-z\-]*)` but this does not catch various items correctly.
This regex is used in main.py in the backend and various files in the frontend.

First of all, the `*` needs to be replaced with a `+` everywhere to make sure that at least one of the items is present: `([A-Z]+[0-9]+|'XX'|[a-z\-]+)` otherwise some items are lost.

Then there are items like `pli-tv-b[iu]-vb-[a-z]+[0-9]+` (f.i. `pli-tv-bu-vb-pj1`) that belong in the collection `pli-tv-bu-vb` or `pli-tv-bi-vb`. As far as I can see these are the only 2 exceptions.

**Comment by TrebuhD** [comment]
@ayya-vimala is this still an issue?

**Comment by ayya-vimala** [comment]
I think this is done in the backend at least. Still an issue in the text view but Sebastian is working on that.
