### ISSUE TITLE
Pali frontend fixes

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#190]
As we discussed, the pali display on the frontend needs some fixes.
I have already created the pali-fixes branch. In this branch, the rendering of the Pali is done in the same way as Sanskrit. @ayya-vimala Please test it thoroughly! I tested it and it works on my local machine, but probably some more testing would be a good idea.
We also need to:
1.  fix the external links to SC in the table-view 
2.  look at the folio-selector in the text-view / loading of folio numbers on the backend
3. test the visual-view for Pali

**Comment by sebastian-nehrdich** [comment]
For the pali folios, the data structure on loading in the backend is as follows
{ "num": "", "segmentnr" : ""} 
The num field is what is displayed in the folio dropdown selector, the segmentnr is the associated first segmentnr of that folio. Its not that complicated after all :D

**Comment by ayya-vimala** [comment]
First PR I have added but the folios is an issue that I also get in the Tibetan. So it shows properly but does not load. It could be that somehow I have not loaded it properly.

**Comment by ayya-vimala** [comment]
All done!
