### ISSUE TITLE
Scrolling up not working

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#193]
In the text view left column the scrolling up is not working.
Also check if right column is working or not.

Go for instance to D4025
Go to one of the last folios
Try to scroll up.
The scrolling does not load again when it reaches it's top point.
Sometimes it does and sometimes it doesn't. It is not always consistent.

**Comment by sebastian-nehrdich** [comment]
I see, I can reproduce it for some folios. I think this is caused by the threshold of the intersection observers. Will look at it tomorrow.
