### ISSUE TITLE
Table view open in new tab not working

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#195]
For pali, in table view, "display this text in new tab" is not working and gives and error:
Cannot GET /pli/text/dn1/dn1:1.1.2_0
Same for the right-hand side of the text-view.

For chinese, in table view it gets into an endless loop with a 404 error.

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich : I had a look at this and I cannot work it out. The URL should work when the last part is set at activeSegment and then the backend does indeed fetch it. But somehow it does not get through that this is the activeSegment while for the Tibetan it works fine. I cannot see a difference between the Tibetan and the Pali in this. Could you please have a look.

**Comment by sebastian-nehrdich** [comment]
I made a PR that fixes the Chinese.
I think for Pali the problem is that the Filename of the URL is not set correctly, while the segmentnr is right. So have a look at what goes wrong with the filename in the construction of the link and then it should become fixable!

**Comment by ayya-vimala** [comment]
The construction is exactly the same as with the tibetan as far as I can see.
The filename is dn1 and when I do `/pli/text/dn1` it loads fine and calls the api request without active_segment set. The segmentnumber in itself would be fine too and when I use Postman to call the api-request that it should become (with active_segment=dn1:1.1.2_0 or active_segment=dn1$3A1.1.2_0) it works just fine. But somehow the segment number is not translated to the active_segment in the URL. 
I will first try to pull your PR for the Chinese and then see if that also fixes pali.

**Comment by ayya-vimala** [comment]
For Tibetan I get for instance a link that looks like `../../tib/text/T06D4020/T06D4020:1b-0` with `textName = T06D4020 and segment=T06D4020:1b-0` and if I use `../../tib/text/T06D4020` instead it loads the file from the start. This is correct. The same with Chinese (now you have changed it). But for the Pali it doesn't seem to get past the router even. 

The link `../../pli/text/dn10/dn10:0.1_0` is correct. `dn10` exists in Arango in files and `dn10:0.1_0` in segments. Both are correct and `../../pli/text/dn10` opens it correctly at the start of the text.
