### ISSUE TITLE
Position of the spinning dharma wheels off

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#2]
Currently (205 branch) the position of the spinning dharma wheel indicating the load process after opening a new file is a bit low. Also the position of the dharma wheel after opening a file on the right side is off, it should be centered in the right column.

**Comment by ayya-vimala** [comment]
Sofar I made a margin-adjust on it and it's not too bad, but maybe you know a better solution (especially for the text-view)
