### ISSUE TITLE
Numbers view returns same values multiple times.

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#282]
![image.png](https://images.zenhubusercontent.com/5cdda43f145f41296ed527b4/bafbd8a0-bd2b-475e-8f75-d44f08028a77)

**Comment by ayya-vimala** [comment]
The return is from the backend but I cannot find out why. Maybe you can have a look

**Comment by sebastian-nehrdich** [comment]
indeed this is a problem of the fact that the graph database is not cleaned properly when rebuilding the database. I will look into this!
