### ISSUE TITLE
Table view sorting by Inquiry Text (and possibly other sorting) not sorted properly.

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#290]
![image.png](https://images.zenhubusercontent.com/5cdda43f145f41296ed527b4/32cb62f1-2621-429d-b8ed-f66feed5760c)

Sorting does not actually seem to be in order. But I can only find this bug in the pali dhammapada so a bit weird.

**Comment by ayya-vimala** [comment]
+ remove redundant sorting option

**Comment by ayya-vimala** [comment]
This bug is still there. This is a screenshot for the sorting in inquiry text:
![image](https://user-images.githubusercontent.com/49606945/103301289-5c5db580-4a01-11eb-9128-fa07cf5ae1ab.png)
So as you see the numbers are not in sorting order.

**Comment by sebastian-nehrdich** [comment]
This one is still a problem, but we will do other things first.

**Comment by sebastian-nehrdich** [comment]
I suspect this is probably a problem in the dataloader.
