### ISSUE TITLE
Improvements to the histogram

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#31]
The histogram still need:
- a title 
- a small information-icon that displays some basic explanation (->Something like "the top 10% of the files are displayed in order according to length as displayed on the x-axis").
Apart from this, very good!

**Comment by ayya-vimala** [comment]
One thing I don't get is any values on the x-axis. Did you have this problem too?

**Comment by sebastian-nehrdich** [comment]
admittedly, I didn't try it yet, will have a look soon!

**Comment by ayya-vimala** [comment]
Don't bother ... I deleted my message because I found it!
