### ISSUE TITLE
Improvements to the visual-view

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#33]
It's pretty good as it is now, just some minor points that should not be forgotten (I will work on these myself now):
- O suggested to have the visual-view sorted by language first. So first one chooses between pali/tibetan/chinese
- if we do it that way, we will actually not have that many options per language. I therefore think that the dropdown menus that we use for the graph-selection at the moment are a bit overkill. Possibly a set of simple buttons will suffice
- currently, we use the filenames layer two/three of the visualization. It would be good to find a way to replace them by the displayName from the menu. 
- the back-button, when used on the third layer, takes one back to the first layer, but it might be better to have it go back to the second layer. not a big problem though.

**Comment by ayya-vimala** [comment]
I think this is all done.
