### ISSUE TITLE
Go back button in local search no longer working

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#330]
Add go-back button to all pages, also those with search results

**Comment by sebastian-nehrdich** [comment]
Feedback from one user: 
One thing that I find needing to look into is the search
function in the Inquiry Text, i.e., the function itself works well as
far as I could see, but there are problems in going back to the text
after the search. If there are no hits we have the "return to text-view"
which too works very well. However, if there are hits but one
nonetheless wish to return to text-view it is a bit of a problem..... I
normally click on one of the links with the file name, but it often get
stuck with the wheel keeping on turning. Maybe we should have the
"return to text-view" option also when there are hits. What do you think?
