### ISSUE TITLE
Segment numbers and linking

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#372]
This is a proposal: 
Right now in Text View clicking on the segment numbers opens the text in that place in a new tab with the relevant segment highlighted.
But in Table View and in the Middle column of Text View, clicking on the segment numbers opens the text in the external website (in pali and chinese with the segment highlighted) while there is a special button to click when you want to open it in a new tab. 

This is a little counter-intuitive. I want to suggest to turn it around: clicking on the segment number everywhere opens up a new tab with the Text View text in BN with the relevant segment highlighted. While an extra button behind the segment opens up the external website.

**Comment by sebastian-nehrdich** [comment]
I agree with this!
