### ISSUE TITLE
Graph view: Show statistics relating to individual files

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#4]
Currently, graph-view collects and displays statistics regarding the categories.
I think it would be very interesting to also show a chart regarding the individual quoted files.
so for D4021 as the main text, this would display D4032 - 5% of all parallels, D4027 - 4,5% of all parallels and so on. 
One could cut the results at a fixed value, for example show the 10 files with the most results, to avoid a pie-chart with hundred of divisions. We could display such a piechart next to the one that we already have. Alternatively, a histogram could also work well. 
I find myself frequently interested in this question, e.g. 'which are the files that have the most parallels with this text'?

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich : not urgent but would the histogram also have to take the filters into account? What do you think?

**Comment by sebastian-nehrdich** [comment]
I would prefer that. I think it would be great to have it be calculated in
a similar fashion we do it with the pie chart now, so the user gets
feedback on the changes of the filters etc., so indeed, that would be great.

**Comment by ayya-vimala** [comment]
If I have some time I might do a little bit on this but not urgent of course. The visual is more urgent to get through first!

**Comment by sebastian-nehrdich** [comment]
Sure! Actually I do believe that these statistics are somewhat important,
so after the visual-view its not a bad time to work on these.
I also discussed a related issue with Orna these days, that is the fact
that we are currently displaying the number of total matches instead of
syllables in the text-view which is not that ideal.
She acknowledges the problem and suggests for the time being to go for a
solution that says "xxx matches have been found with a total length of yyy
syllables ..."
She would very much like to see more detailed statistics about this. E.g.
:150 matches shorter than 100 syllables, 40 matches longer than 100 but
shorter than 200 syllables' etc.
I think this would ge very much in the similar direction of what we are
planning to do  with the histogram, so at some point (not urgent) we can
think about adding this information as well!

**Comment by ayya-vimala** [comment]
So what is a "syllable" in this? Is this the length-count? And the 'matches' are the number of parallels found i.e. if abc1:1-3 equals xyz3:3-4 that is one match?
Or does it have to do with co-occurances?
So for the histogram, on the basis of what exactly? Right now the pie-chart works on the basis of length-count.
