### ISSUE TITLE
Space saving solutions for header

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#407]
The header takes currently a lot of space, especially on small screens.

Space saving solutions to try:
1. retractable search buttons
2. move transliteration to settings
3. put view-selection into dropdown or so
4. make full-screen mode truly fullscreen

**Comment by thesunshade** [comment]
![image](https://user-images.githubusercontent.com/82448383/127833960-a5bd499b-c499-428b-b1e7-e3fa2a64bdb0.png)
Here is what the site looks like on a 13.5" screen, regular view.

![image](https://user-images.githubusercontent.com/82448383/127834217-fbb3908c-92d7-460c-b378-05b41b1c4119.png)
Here is "Full Screen" view. Better, but the text is still only visible in 50% of the screen

**Comment by ayya-vimala** [comment]
Thank you @thesunshade (aka Snowbird :smile: ). It is helpful to see screenshots!
