### ISSUE TITLE
small changes to table download dialogbox

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#435]
After reviewing the changes with the rest of the team, the following steps are desirable: 
- don't close the dialogbox when the download is ready
- add a button with the download link with a message 'download is ready' below the 'This can take some time. Your download will start when ready. In the mean time you can continue working.' text 
- we can continue to keep the behavior of the download starting automaticly

**Comment by ayya-vimala** [comment]
You cannot change the content of the dialogbox once rendered but I worked around that by closing that one and opening a new one.
