### ISSUE TITLE
Create manual of different elements on the site

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#49]
User tutorial for the different elements on the site.
Cannot be done before the design is finalized.
Sebastian to speak with Orna about what is needed exactly.

Two suggestions:
https://introjs.com/ <-- for the tutorial
https://shepherdjs.dev/ <-- another one

**Comment by sebastian-nehrdich** [comment]
We now have the guidelines and the information buttons. Do we still need this issue?

**Comment by ayya-vimala** [comment]
I guess not. We can always make the youtube videos to show how to do things.
