### ISSUE TITLE
infinite scrolling does not work optimally

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#56]
Infinite scrolling should be in a way that the user does not notice it so some work needs to be done on this as right now it keeps showing the loading spinner and stops at the end before loading more data.

**Comment by TrebuhD** [comment]
@ayya-vimala is this about a specific view / page or generally? Can we list the places that have this problem?

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich - I think this is about the text-view left and right only isn't it?

**Comment by sebastian-nehrdich** [comment]
This addresses indeed only the left and right text-view.
