### ISSUE TITLE
text-view on the left side does not respond correctly to multiple filter settings

### ISSUE THREAD

**Issue by sebastian-nehrdich** [BuddhaNexus/buddhanexus-frontend#88]
To reproduce: open Td4055, set "Limit to files" to "TD4064" and "exclude collections" to "Kengyur (ALL)". Now only 39 parallels should be shown, but instead of that all parallels are shown.
I suspect the bug happening on the backend in the query QUERY_TEXT_AND_PARALLELS, where the limitCollection settings are not applied correctly.

**Comment by ayya-vimala** [comment]
1. Maybe best to solve this after move to graph database.
2. Of course if you limit the collection to one file and then exclude other files, the exclude is superfluous.
3. I tested it on pali, that worked well.
4. I tried testing on Tibetan but ran into other issues like the limit filelist does doesn't go further then T02 ... maybe a setting somewhere that only returns 1000 results or so. So I tried it with some of those files and it worked fine.
5. At some point it all starts to stall: it cannot get the request from the backend and the loader-wheel keeps on spinning. Maybe refactoring will solve this.

**Comment by sebastian-nehrdich** [comment]
Where did you test the tibetan? If I test it on https://buddhanexus.kc-tbts.uni-hamburg.de/tib/text, I get the full filelist in the filters. 
Regarding (5), I am very sure this is a backend issue, precisely in the function create_cleaned_limit_collection(). I could trace the error-message to that function when I run the filter request described in the inital issue on D4055 locally, but since I don't know very well how it is supposed to work I didn't propose a PR for it yet. Maybe you can have a look?
