### ISSUE TITLE
Filter box in side-sheet dropdown menu

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#90]
Right now the filters become a very large area that pushes down the text. It will be better to have it as a side-sheet according to: https://material.io/components/sheets-side/#

Examples:
https://github.com/suttacentral/suttacentral/blob/master/client/elements/menus/sc-more-menu.js
https://github.com/milieuinfo/webcomponent-vl-ui-side-sheet

**Comment by TrebuhD** [comment]
Specifications of the side sheet I'll implement: https://material.io/components/sheets-side/#theming

**Comment by TrebuhD** [comment]
Ready to review.
