### ISSUE TITLE
Python script for pali diacritics

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#95]
Write a python function that removes pali diacritics from the text.

Also ask Blake for a script that looks at verb forms.

**Comment by ayya-vimala** [comment]
@sebastian-nehrdich : Here is your function:
```
diacritics_conversion_dict = {
    'ā': 'a',
    'ī': 'i',
    'ū': 'u',
    'ṭ': 't',
    'ḍ': 'd',
    'ṅ': 'n',
    'ṇ': 'n',
    'ñ': 'n',
    'ḷ': 'l',
    'ṃ': 'm',
    'ṁ': 'm',
    'ś': 's',
    'ṣ': 's',
    'ḥ': 'h',
    'ṛ': 'r',
    'ṝ': 'r',
    'ḹ': 'l'
}

def remove_diacritics(line):
    newline = ''
    for character in line:
        if character in diacritics_conversion_dict.keys():
            newline += diacritics_conversion_dict[character]
        else:
            newline += character
    return(newline)
```
Maybe there is some abreviated way of writing this too in python

**Comment by ayya-vimala** [comment]
You can also make newline an array [] and then append each character to that and in the end join them with `''.join()`

**Comment by sebastian-nehrdich** [comment]
this reminds me of the fact that I always wanted to train a neural network to reconstruct lost diacritics :D and this script is the perfect tool to create the training data for that task! thanks!
